apiVersion: v1
kind: Service
metadata:
  name: frontend-external
spec:
  type: NodePort
  selector:
    app: frontend-external
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 32002
